@startuml cnn4

<style>
activityDiagram {
  BackgroundColor #FFFF00
  BorderColor #33668E
  FontColor #000000
  FontName arial
}

document {
   BackgroundColor gray
}
</style>
split
    -[hidden]->
    :TRAINING ARGUMENTS;
split again
    -[hidden]->
    :EVALUATION;
end split
partition TRAINER {
    split
        :model;
    split again
        :args;
    split again
        :train_dataset;
    split again
        :eval_dataset;
    split again
        :compute_metrics;
    split again
        :data_collator;
    split again
        split
            :early_stopping;
        split again
            :training_logs;
        end split
    end split
}
:RESULTS;
@enduml
